language: node_js

sudo: false

cache:
  directories:
    - /client/tardis/node_modules

node_js:
  - node
  - "8.10"

before_script:
  - cd client/tardis
  - npm install

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change